### ISSUE TITLE
AWS/ElasticInterface seems to have been renamed to AWS/ElasticInference

### ISSUE THREAD

**Issue by haedri** [claranet/terraform-signalfx-integrations#72]
https://github.com/claranet/terraform-signalfx-integrations/blob/db2d494bdc88f4efa3b2297c37b75f864b7cbef1/cloud/aws/variables.tf#L126

Could not find source for this change, just an update in the official documentation
https://github.com/splunk/public-o11y-docs/commit/12407dfccd43e523816e9bba4391b34d254b749f

**Comment by pdecat** [comment]
I believe `AWS/ElasticInterface` never existed.
